workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"

image: "vgitlab01.tq-net.de:5005/tq-embedded/tqmaxx/toolchain-tqmaxx/bare:ubuntu-22.04"

variables:
  OEI_CROSS_COMPILE: "/opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-"

stages:
  - build

compile:
  tags:
    - docker
    - tqmaxx
  stage: build
  parallel:
    matrix:
      - MACHINE: [ "tqma95xxsa", "tqma95xxla" ]
        CONFIG: [ "d=1 t=1", "d=0" ]
        REV: [ "B0" ]
        IMAGE: [ "ddr", "tcm" ]
        DDR_CONFIG: [ "TQMa95xxSA.DDR-Timing.2GB.V25.06.0006", "TQMa95xxSA.DDR-Timing.4GB.V25.06.0006" ]
      - MACHINE: [ "tqma94xxla" ]
        CONFIG: [ "d=1 t=1", "d=0" ]
        REV: [ "A0" ]
        IMAGE: [ "ddr" ]
        DDR_CONFIG: [ "TQMa94xxLA.DDR-Timing.2GB.V25.12.0001" ]
  script:
    - echo "Building ${MACHINE} with ${CONFIG}"
    - make -j$(nproc) board=${MACHINE} oei=${IMAGE} r=${REV} ${CONFIG} DDR_CONFIG=${DDR_CONFIG} BUILD=${DDR_CONFIG} all
  artifacts:
    when: on_success
    paths:
      - "${DDR_CONFIG}/${MACHINE}/${IMAGE}/*.bin"
      - "${DDR_CONFIG}/${MACHINE}/${IMAGE}/*.elf"
      - "${DDR_CONFIG}/${MACHINE}/${IMAGE}/*.map"
      - "${DDR_CONFIG}/${MACHINE}/${IMAGE}/build_info.h"
