workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"

image: "vgitlab01.tq-net.de:5005/tq-embedded/tqmaxx/toolchain-tqmaxx/bare:ubuntu-18.04"

variables:
  OEI_CROSS_COMPILE: "/opt/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-"
  BUILDDIR: build

stages:
  - build

compile:
  tags:
    - docker
    - tqmaxx
  stage: build
  parallel:
    matrix:
      - MACHINE: [ "tqma95xxsa" ]
        CONFIG: [ "d=1", "d=0" ]
        RAM_SIZE: [ "2", "4" ]
  script:
    - echo "Building ${MACHINE} with ${CONFIG}"
    - make -j$(nproc) board=${MACHINE} oei=tcm ${CONFIG} RAM_SIZE=${RAM_SIZE} all
    - make -j$(nproc) board=${MACHINE} oei=ddr ${CONFIG} RAM_SIZE=${RAM_SIZE} all
  artifacts:
    when: on_success
    paths:
      - "${BUILDDIR}/${MACHINE}/*/*.bin"
      - "${BUILDDIR}/${MACHINE}/*/*.elf"
      - "${BUILDDIR}/${MACHINE}/*/build_info.h"
